# Generated by Django 4.0.2 on 2022-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
