# Generated by Django 4.0.2 on 2022-02-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapps', '0002_alter_like_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likes',
            new_name='liked_date',
        ),
    ]
